services:
  proxy:
    build: .
    profiles:
      - with_proxy
    environment:
      MITTWALD_EXT_PROXY_API_BASE_URL: http://localhost:8080/v2
      MITTWALD_EXT_PROXY_UPSTREAMS: '{"/":{"upstreamURL":"http://httpbin.org"}}'
      MITTWALD_EXT_PROXY_CONTEXT: dev
      MITTWALD_EXT_PROXY_SECRET: secret
      MITTWALD_EXT_PROXY_MONGODB_URI: mongodb://admin:secret@mongodb:27017
      PORT: 8000
    ports:
      - 8000:8000
  devserver:
    image: mittwald/marketplace-local-dev-server:latest
    volumes:
      - .env:/.env
    ports:
      - 8080:8080
  mongodb:
    image: mongo:8
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
